version: "3"
services:
  app:
    image: kanchan-slate-graphql
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"